version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - dependabot
      - enhancement
  - package-ecosystem: bundler
    directory: /docs
    schedule:
      interval: daily
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - dependabot
      - enhancement
  - package-ecosystem: npm
    directory: /jsonresume
    schedule:
      interval: daily
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - dependabot
      - enhancement
