title: 广东省科学院智能制造研究所人因工程团队

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year/:month/:day/:title

csv_reader:
  converters:
    - date
  headers: true
  encoding: utf-8

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - CNAME

theme:
remote_theme:

# TODO: unsafe API credentials, consider using proxy instead (https://lbs.amap.com/api/jsapi-v2/guide/abc/load)
amap:
  key: 2767bf8a43da00d42c477e4a08f3dea6
  secret: 257694db4842ca764542d1fa58f7379a
