title: 广东省科学院智能制造研究所人因工程团队

collections:
  solutions:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year/:month/:day/:title

csv_reader:
  converters:
    - date
  headers: true
  encoding: utf-8

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - CNAME

theme:
remote_theme:

amap:
  key: cbe41f176a2bce88bc10a89de685be1e
