title: 广东省科学院智能制造研究所人因工程团队

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year-:month-:day-:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - CNAME
