name: 广东省科学院智能制造研究所人因工程团队
title: 广东省科学院智能制造研究所人因工程团队

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - CNAME
